name: Release

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'

jobs:
  build:
    name: Upload Release Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: exe

    steps:
      - name: Set envs
        id: vars
        shell: bash
        run: |
          echo ::set-output name=ver::1.2.1
          # echo ::set-output name=ver::${GITHUB_REF/refs\/tags\/v/}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build package
        shell: pwsh
        run: |
          rustup target add ${{ matrix.target }}
          choco install llvm
          cargo build --features oniguruma --release --verbose --target x86_64-pc-windows-msvc
          # => target\x86_64-pc-windows-msvc\release\teip.exe will be created
          Invoke-WebRequest -OutFile windows\wizard.bmp -Uri https://raw.githubusercontent.com/wiki/greymd/teip/img/wizard.bmp
          md windows\exe
          Move-Item target\x86_64-pc-windows-msvc\release\teip.exe windows\exe
          & "${Env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe" windows\installer.iss
          Move-Item windows\Output\teip_installer.exe .
          Rename-Item teip_installer.exe teip_installer-${{ steps.vars.outputs.ver }}-${{ matrix.target }}.exe

      - name: Upload binaries to release for Windows
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: teip_installer-${{ steps.vars.outputs.ver }}-${{ matrix.target }}.${{ matrix.ext }}
          asset_name: teip_installer-${{ steps.vars.outputs.ver }}-${{ matrix.target }}.${{ matrix.ext }}
          # tag: ${{ github.ref }}
          tag: v1.2.1
          overwrite: true