name: Test for Windows

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: test
    runs-on: ${{matrix.os}}
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: exe

    steps:
      - uses: actions/checkout@v2
      - name: Prepare sed which supports UTF-8
        run: |
          Invoke-WebRequest https://github.com/mbuilov/sed-windows/raw/master/sed-4.9-x64.exe -UseBasicParsing -OutFile sed.exe
          Move-Item -Force sed.exe "C:\Program Files\Git\usr\bin\seq.exe"
        shell: powershell
      - name: Build the release target
        run: |
          rustup target add ${{ matrix.target }}
          choco install llvm
          cargo build --features oniguruma --release --verbose --target x86_64-pc-windows-msvc
          # => target\x86_64-pc-windows-msvc\release\teip.exe will be created
      - name: Run tests
        timeout-minutes: 10
        run: cargo test --verbose --features oniguruma
